### ISSUE TITLE
Increase the font size of text and use textarea instead input.

### ISSUE THREAD

**Issue by ashsajal1** [ashsajal1/typing-app#10]
**Describe the solution you'd like**
Clearly outline the solution you are requesting. In this case, specify that the font size of the text should be increased, and a textarea should be used instead of an input field.

**Comment by RahalBhupathi** [comment]
Hello, can I please be assigned to this task? I am a new developer looking for first contributions.

**Comment by RahalBhupathi** [comment]
@ashsajal1 I put in a pull request with the changes, please review.
