### ISSUE TITLE
Add status in result. Consider adding emoji or some illustration.

### ISSUE THREAD

**Issue by ashsajal1** [ashsajal1/typing-app#12]

**Comment by RahalBhupathi** [comment]
Hello, I've went ahead and implemented this with 4 status levels based on accuracy and wpm. I'll submit a draft pr with the criteria I currently have defined, please advise if any changes are needed. Currently the criteria for status I have are:
"Excellent!" - 90%+ Accuracy, 60+ wpm
"Great Job!" - 80%+ Accuracy, 50+ wpm
"Good Effort!" - 70%+ Accuracy, 40+ wpm
"Keep Practicing!" - sub 70% accuracy, sub 40 wpm
