### ISSUE TITLE
Add a restart button.

### ISSUE THREAD

**Issue by andrew-zachary** [ashsajal1/typing-app#14]

**Comment by ashsajal1** [comment]
Oh, that was very basic thing I missed to do. Thank you.

**Comment by andrew-zachary** [comment]
Good luck, mate!

**Comment by RahalBhupathi** [comment]
I'd like to implement this, but I have a few questions. Adding a reset button could be as simple as tying a button to refresh the window, but this will not preserve the word list. Should the user be shown the same set of words after a reset, or should they get a new random set of words?

**Comment by ashsajal1** [comment]
> I'd like to implement this, but I have a few questions. Adding a reset button could be as simple as tying a button to refresh the window, but this will not preserve the word list. Should the user be shown the same set of words after a reset, or should they get a new random set of words?

New random set of words. @RahalBhupathi

**Comment by ashsajal1** [comment]
Create a branch of this issue and then work on it.
